// This file is auto-generated by scripts/generate-level-loaders.mjs
// Do not edit manually.

import type { TaskType } from "@/context/app.context.reducer";

type LevelModule = Partial<Record<`LEVEL_${number}`, TaskType[]>>;
type LevelLoader = () => LevelModule;

export const LEVEL_LOADERS: Record<number, LevelLoader> = {
  1: () => require("@/data/math-1-level"),
  2: () => require("@/data/math-2-level"),
  3: () => require("@/data/math-3-level"),
  4: () => require("@/data/math-4-level"),
  5: () => require("@/data/math-5-level"),
  6: () => require("@/data/math-6-level"),
  7: () => require("@/data/math-7-level"),
  8: () => require("@/data/math-8-level"),
  9: () => require("@/data/math-9-level"),
  10: () => require("@/data/math-10-level"),
  11: () => require("@/data/math-11-level"),
  12: () => require("@/data/math-12-level"),
  13: () => require("@/data/math-13-level"),
  14: () => require("@/data/math-14-level"),
  15: () => require("@/data/math-15-level"),
  16: () => require("@/data/math-16-level"),
  17: () => require("@/data/math-17-level"),
  18: () => require("@/data/math-18-level"),
  19: () => require("@/data/math-19-level"),
  20: () => require("@/data/math-20-level"),
  21: () => require("@/data/math-21-level"),
  22: () => require("@/data/math-22-level"),
  23: () => require("@/data/math-23-level"),
  24: () => require("@/data/math-24-level"),
  25: () => require("@/data/math-25-level"),
  26: () => require("@/data/math-26-level"),
  27: () => require("@/data/math-27-level"),
  28: () => require("@/data/math-28-level"),
  29: () => require("@/data/math-29-level"),
  30: () => require("@/data/math-30-level"),
  31: () => require("@/data/math-31-level"),
  32: () => require("@/data/math-32-level"),
  33: () => require("@/data/math-33-level"),
  34: () => require("@/data/math-34-level"),
  35: () => require("@/data/math-35-level"),
  36: () => require("@/data/math-36-level"),
  37: () => require("@/data/math-37-level"),
  38: () => require("@/data/math-38-level"),
  39: () => require("@/data/math-39-level"),
  40: () => require("@/data/math-40-level"),
  41: () => require("@/data/math-41-level"),
  42: () => require("@/data/math-42-level"),
  43: () => require("@/data/math-43-level"),
  44: () => require("@/data/math-44-level"),
  45: () => require("@/data/math-45-level"),
  46: () => require("@/data/math-46-level"),
  47: () => require("@/data/math-47-level"),
  48: () => require("@/data/math-48-level"),
  49: () => require("@/data/math-49-level"),
  50: () => require("@/data/math-50-level"),
  51: () => require("@/data/math-51-level"),
};

export const GENERATED_TOTAL_LEVELS = 51;
